packages:
  - .
autoInstallPeers: false
minimumReleaseAge: 0

overrides:
  reflect-metadata: "$reflect-metadata"
  koa: ^3.2
allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  core-js: true
  esbuild: true
  unrs-resolver: true
