name: publish Type Package
on:
    push:
        tags:
            - type-v*
jobs:
    Build-and-Publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 9
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://npm.pkg.github.com
                  cache: pnpm
            - name: Install, Build & Publish
              run: |
                  pnpm i  &&  pnpm build
                  cd type/
                  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
